### ISSUE TITLE
GiveHelp--TODO

### ISSUE THREAD

**Issue by priyasubramanian21** [priyasubramanian21/jannSeva#1]
- [x] status maintenance (pending , open ,completed )
- [x] last user (i.e origin of reference ) - set initial open - onces completed - last to next user  status changed into open - looping 
- [x] on click  open - show page  clicked user details - click submit .
- [x] set notification option 
- [x] send notification on referral user 
- [x] permit notification  (accept) - referral user 
- [x] change status on last user .
