### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by priyasubramanian21** [priyasubramanian21/jannSeva#5]
- [x] Referral link
- [x] based on sign up connect method
- [x] chart percentage
- [x] pmf - multicheck based pay
- [x] pmf pay - need to check
- [x] chart more than 5 referral check
- [x] fix all notice and warning
- [x] overall work flow
