### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by priyasubramanian21** [priyasubramanian21/jannSeva#6]
- [x] Password reset - option - profile
- [x] mobile number disable in profile
- [x] give help need to check
- [x] change get to post
- [x] after completing payment process in  give help then only start receive help

**Comment by priyasubramanian21** [comment]
Completed
